DELETE FROM name_2
WHERE (ID,NAME,AGE,COUNTRY,SALARY) IN (
  SELECT ID,NAME,AGE,COUNTRY,SALARY
  FROM name_2
  GROUP BY ID,NAME,AGE,COUNTRY,SALARY
  HAVING COUNT(*) > 1
);

CREATE TABLE temp AS
SELECT DISTINCT ID,NAME,AGE,COUNTRY,SALARY
FROM name_2;
delete from name_2;
INSERT INTO name_2(ID,NAME,AGE,COUNTRY,SALARY)
SELECT ID,NAME,AGE,COUNTRY,SALARY
FROM temp;
drop table temp;